Garcia-Changes
merces/libpe pull request #33
Opened 2021-02-15 22:04 UTC by fgarcia0x0

- add big improvement's in libpe.
- add error checking for some mechanism.
- refactored code in some parts.

2021-02-22 22:51 UTC, merces commented on hashes.c
> +	do { cond ? abort() : (void)0; } while (0)
Improvement: use `(cond)`

2021-02-22 23:01 UTC, merces commented on hashes.c
> +static void pev_get_elem_func_name(element_t* elem_ptr, ord_t* ord_ptr, int hint)
We should pick up a better name.

2021-02-22 23:40 UTC, merces requested changes
Please review. Have a look at [these](https://www.onlinegdb.com/fork/Q1CPEpu6t) test cases.

2021-02-23 01:32 UTC, fgarcia0x0 commented
all warning and pendencies has fixed

2021-02-23 01:32 UTC, fgarcia0x0 commented
all warning and pendencies has fixed

2021-02-23 02:10 UTC, merces approved these changes
These are great! Thanks!

2021-02-23 02:10 UTC, merged